version: "3"

# configuring the default network to be the replicaset_cluster network
networks:
  default:
    external: true
    name: replicaset_cluster_mongo_net_rs1

services:
  #tcp data server container
  tcp_server:
    container_name: tcp_server
    build: ./tcp_server
    restart: always
    ports:
      - 8282:8282

  client:
    container_name: client
    build: ./client
    depends_on:
      - tcp_server
    restart: always
    environment:
      MONGODB_URI: $MONGO_URI
      DB_NAME: $DB_NAME
      DB_PASS: $MONGO_PW
